spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud-service
          uri: lb://fraud-service
          predicates:
            - Path=/api/v1/fraud-check/**

server:
  port: 8083


eureka:
  client:
    service-url: { defaultZone: http://localhost:8761/eureka }
    fetch-registry: true
    register-with-eureka: true