server:
  port: 8081
spring:
  application:
    name: fraud-service
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost/fraud
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url: { defaultZone: http://localhost:8761/eureka }
    fetch-registry: true
    register-with-eureka: true